version: '3.4'

services:
  httpd:
    environment:
      - VIRTUAL_HOST=backend.byteporter.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=backend.byteporter.com
      - LETSENCRYPT_EMAIL=webmaster@byteporter.com

networks:
  net:
    external:
      name: docker-reverse-proxy_net
