version: '3.4'

services:
  httpd:
    image: nouchka/sqlite3
    volumes:
      - ../backend:/usr/share/backend/backend:ro
      - ../assets/backend.db:/usr/share/backend/assets/backend.db:rw
      - ../web:/usr/share/backebd/web:ro
    networks:
      - net
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=backend.byteporter.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=backend.byteporter.com
      - LETSENCRYPT_EMAIL=webmaster@byteporter.com
    entrypoint: ["/bin/backend"]
    restart: always
  adminer:
    # Adminer 4.8.0 shows an error with SQLite3 db files. This is fixed in
    # version 4.8.1 but at the time I'm writing this stack, 4.8.0 is the
    # newest version of the docker image. Rolled back to previous version to
    # avoid the bug.
    image: adminer:4.7.9
    volumes:
      - ../assets/backend.db:/var/www/html/backend.db:rw
      - ./login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php:ro
    ports:
      - "8081:8080"

networks:
  net:
    #     external:
    #       name: docker-reverse-proxy_net
