---
kind: pipeline
type: docker
name: default

steps:
  - name: build-backend
    image: docker.byteporter.com/backend/build-env
    commands:
      - make

image_pull_secrets:
  - dockerconfigjson

trigger:
  event:
    - push
  branch:
    - master
