---
kind: pipeline
type: docker
name: default

steps:
  - name: build-backend
    image: docker.byteporter.com/backend/build-env
    commands:
      - make

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      auto_tag: true
      repo: good-brain-thinkins/backend
      dockerfile: build/package/docker/backend/Dockerfile
      registry: docker.byteporter.com

image_pull_secrets:
  - dockerconfigjson

trigger:
  event:
    - push
  branch:
    - master
