---
kind: pipeline
type: docker
name: default

steps:
  - name: build-backend
    image: docker.byteporter.com/backend/build-env
    commands:
      - make

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      auto_tag: true
      # custom registry MUST be repeated here or it tries to use
      # docker.io as the registry
      repo: docker.byteporter.com/good-brain-thinkins/backend
      dockerfile: build/package/docker/backend/Dockerfile
      registry: docker.byteporter.com
    when:
      event:
        - tag

image_pull_secrets:
  - dockerconfigjson

trigger:
  event:
    - push
    - tag
